# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Shibaken28"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/Shibak33333333n"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "steam"
name = "steam"
url = "https://steamcommunity.com/profiles/76561199155194438/"

[social.params]
icon = ""


